// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package formrecognizer.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines headers for AnalyzeLayoutAsync operation.
 */
@Fluent
public final class AnalyzeLayoutAsyncHeaders {
    /*
     * URL containing the resultId used to track the progress and obtain the
     * result of the analyze operation.
     */
    @JsonProperty(value = "Operation-Location")
    private String operationLocation;

    /**
     * Get the operationLocation property: URL containing the resultId used to
     * track the progress and obtain the result of the analyze operation.
     *
     * @return the operationLocation value.
     */
    public String getOperationLocation() {
        return this.operationLocation;
    }

    /**
     * Set the operationLocation property: URL containing the resultId used to
     * track the progress and obtain the result of the analyze operation.
     *
     * @param operationLocation the operationLocation value to set.
     * @return the AnalyzeLayoutAsyncHeaders object itself.
     */
    public AnalyzeLayoutAsyncHeaders setOperationLocation(String operationLocation) {
        this.operationLocation = operationLocation;
        return this;
    }
}
