// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package formrecognizer.implementation;

import com.azure.core.annotation.BodyParam;
import com.azure.core.annotation.Delete;
import com.azure.core.annotation.ExpectedResponses;
import com.azure.core.annotation.Get;
import com.azure.core.annotation.Host;
import com.azure.core.annotation.HostParam;
import com.azure.core.annotation.PathParam;
import com.azure.core.annotation.Post;
import com.azure.core.annotation.QueryParam;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClientBuilder;
import com.azure.core.annotation.ServiceInterface;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.annotation.UnexpectedResponseExceptionType;
import com.azure.core.http.HttpPipeline;
import com.azure.core.http.HttpPipelineBuilder;
import com.azure.core.http.policy.CookiePolicy;
import com.azure.core.http.policy.RetryPolicy;
import com.azure.core.http.policy.UserAgentPolicy;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.http.rest.VoidResponse;
import formrecognizer.FormRecognizerClient;
import formrecognizer.models.AnalyzeLayoutAsyncResponse;
import formrecognizer.models.AnalyzeOperationResult;
import formrecognizer.models.AnalyzeReceiptAsyncResponse;
import formrecognizer.models.AnalyzeWithCustomModelResponse;
import formrecognizer.models.ErrorResponseException;
import formrecognizer.models.Model;
import formrecognizer.models.ModelsModel;
import formrecognizer.models.TrainCustomModelAsyncResponse;
import formrecognizer.models.TrainRequest;
import java.util.UUID;
import reactor.core.publisher.Mono;

/**
 * A builder for creating a new instance of the FormRecognizerClient type.
 */
@ServiceClientBuilder(serviceClients = FormRecognizerClient.class)
public final class FormRecognizerClientBuilder {
    /*
     * Supported Cognitive Services endpoints (protocol and hostname, for example: https://westus2.api.cognitive.microsoft.com).
     */
    private String endpoint;

    /**
     * Sets Supported Cognitive Services endpoints (protocol and hostname, for example: https://westus2.api.cognitive.microsoft.com).
     *
     * @param endpoint the endpoint value.
     * @return the FormRecognizerClientBuilder.
     */
    public FormRecognizerClientBuilder endpoint(String endpoint) {
        this.endpoint = endpoint;
        return this;
    }

    /*
     * The HTTP pipeline to send requests through
     */
    private HttpPipeline pipeline;

    /**
     * Sets The HTTP pipeline to send requests through.
     *
     * @param pipeline the pipeline value.
     * @return the FormRecognizerClientBuilder.
     */
    public FormRecognizerClientBuilder pipeline(HttpPipeline pipeline) {
        this.pipeline = pipeline;
        return this;
    }

    /**
     * Builds an instance of FormRecognizerClient with the provided parameters.
     *
     * @return an instance of FormRecognizerClient.
     */
    public FormRecognizerClient build() {
        if (pipeline == null) {
            this.pipeline = new HttpPipelineBuilder().policies(new UserAgentPolicy(), new RetryPolicy(), new CookiePolicy()).build();
        }
        FormRecognizerClientImpl client = new FormRecognizerClientImpl(pipeline);
        if (this.endpoint != null) {
            client.setEndpoint(this.endpoint);
        }
        return client;
    }
}
