// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

/**
 * Package containing the implementations and inner classes for
 * FormRecognizerClient.
 * Extracts information from forms and images into structured data.
 */
package formrecognizer.implementation;
